[package]
name = "learn_5_3_struct_method"
version = "0.1.0"
authors = ["Xuhua Huang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
