[package]
name = "learn_1_2_hello_rust"
version = "0.1.0"
authors = ["Xuhua Huang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
