[package]
name = "learn_5_2_struct_rectangle"
version = "0.1.0"
authors = ["1879700"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
