[package]
name = "_1_2_hello_rust"
version = "0.1.0"
authors = ["1879700"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
